### ISSUE TITLE
Llama 3 Model Support

### ISSUE THREAD

**Issue by antmikinka** [huggingface/swift-transformers#103]
I converted [Llama 3 8B Instruct ](https://huggingface.co/anthonymikinka/Meta-Llama-3-8B-Instruct )to CoreML. 

This does not have KV Cache. only: inputs int32 / outputs float16.

I haven't been able to test this, so leave something in 'Community' to let me know how ya tested it and how it worked.

I did model.half() before scripting / converting thinking it would reduce my memory usage (I found online that it doesn't).

I am unsure if it affected the conversion process or not.

Unfortunately, haven't gotten to working on the Llama 3 tokenizer for supporting it. I plan on working it.

**Comment by KrisSimon** [comment]
Maybe that helps to optimize https://machinelearning.apple.com/research/core-ml-on-device-llama

**Comment by antmikinka** [comment]
@KrisSimon Thanks for letting me know this looks pretty interesting!
Just read through it! Wild that there is no one converting the llama's to CoreML and uploading them. Maybe I'll give it a shot in the future after a computer upgrade.

Btw, I posted all my code work for the HF Model Upload here:
https://github.com/antmikinka/LlamaCoreMLOptimized
