### ISSUE TITLE
Not able to run the Mistral 7B int4 and FP 16 on Mac OS 15.1 and Mac OS 15.0

### ISSUE THREAD

**Issue by kevin36524** [huggingface/swift-transformers#112]
Issue: Getting error `Error: The data couldn’t be read because it isn’t in the correct format.` when trying out swift run transformers with mistral-7B 4bit quantization.

OS Version : Mac OS 15.1 Beta (24B5009l)
Xcode version: Version 16.0 beta 3 (16A5202i)
Machine: Mac mini 2023 -  M2  - 8GB 

### Repro steps
Step 1: Clone the preview branch of the swift-transformers repo: `git clone -b preview https://github.com/huggingface/swift-transformers` 
Step 2: Download the converted Core ML models from [this Hugging Face repo](https://huggingface.co/apple/mistral-coreml) 
Step 3: Run inference using Swift: `swift run transformers "Best recommendations for a place to visit in Paris in August 2024:" --max-length 200 Mistral7B-CoreML/StatefulMistralInstructInt4.mlpackage`

### Output 

```
(venv) kevin@Mac swift-transformers % swift run transformers "Best recommendations for a place to visit in Paris in August 2024:" --max-length 128 Examples/Mistral7B/StatefulMistral7BInstructInt4.mlpackage

Building for debugging...
[1/1] Write swift-version-39B54973F684ADAB.txt
Build of product 'transformers' complete! (0.17s)
Compiling model Examples/Mistral7B/StatefulMistral7BInstructInt4.mlpackage -- file:///Users/arforgeqa/Projects/swift-transformers/
Loading model file:///var/folders/4x/2n2whrg17s7g6s9xcr67tmt80000gn/T/StatefulMistral7BInstructInt4_A3224709-606B-4B0E-B497-34BD3B7C7FA1.mlmodelc
Generating
Error: The data couldn’t be read because it isn’t in the correct format.
```

Even tried with FP16 still no luck
```
(venv) kevin@Mac swift-transformers % swift run transformers "Best recommendations for a place to visit in Paris in August 2024:" --max-length 128 models/StatefulMistral7BInstructFP16.mlpackage            

Building for debugging...
[1/1] Write swift-version-39B54973F684ADAB.txt
Build of product 'transformers' complete! (0.17s)
Compiling model models/StatefulMistral7BInstructFP16.mlpackage -- file:///Users/arforgeqa/Projects/swift-transformers/
Loading model file:///var/folders/4x/2n2whrg17s7g6s9xcr67tmt80000gn/T/StatefulMistral7BInstructFP16.mlmodelc
Generating
Error: The data couldn’t be read because it isn’t in the correct format.
```

**Comment by pcuenca** [comment]
Hello @kevin36524! I haven't tested 15.1 yet (I'm on the 15.0 beta track). Other than that, did you verify that your downloads were correct? Just in case, here are the package sizes for reference:

<img width="548" alt="Screenshot 2024-08-02 at 10 16 34" src="https://github.com/user-attachments/assets/37be9f30-c84d-4082-a23e-aced2e9a1094">

**Comment by kevin36524** [comment]
Hey @pcuenca Thanks for your prompt response, yes I checked the sizes and they seemed correct.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/d19444d9-9279-44f7-b510-f5df6a6a4239">

**Comment by kevin36524** [comment]
Sorry for sounding like a broken record, I also tried with the public beta Mac OS 15.0 but still no luck. Starting to feel like the issue is with M2 Macs or Mac mini.

```
kevin@Kevins-Mac-mini swift-transformers % swift run transformers "Best recommendations for a place to visit in Paris in August 2024:" --max-length 200 ../models/StatefulMistral7BInstructInt4.mlpackage
Building for debugging...
[1/1] Write swift-version-39B54973F684ADAB.txt
Build of product 'transformers' complete! (0.20s)
Compiling model ../models/StatefulMistral7BInstructInt4.mlpackage -- file:///Users/kevin/projects/swift-transformers/
Loading model file:///var/folders/wl/tr847nmj2sz6b_w6qyyxmbr80000gn/T/StatefulMistral7BInstructInt4_7BD6DCDA-C400-4F98-BC40-60EB2CD88625.mlmodelc
Generating
Error: The data couldn’t be read because it isn’t in the correct format.
```
![image](https://github.com/user-attachments/assets/9adbdea4-8cda-4c0e-bc96-1e16c800ae07)

**Comment by kevin36524** [comment]
Fixed the issue. The main issue was that the tokenizer was not getting downloaded as the 

`HUGGING_FACE_HUB_TOKEN` was not set in my environment  variable. 

Once that was added, I had to clear out my huggingface directory in Documents folder

`rm -rf ~/Documents/huggingface`

and then re-run the command

**Comment by pcuenca** [comment]
Oh, glad you were able to find the issue, but it's unfortunate that the error message was not clear enough.

**Comment by kevin36524** [comment]
Thanks @pcuenca . Yeah, If you don't mind can I raise a PR to make the error message more meaningful ?

**Comment by pcuenca** [comment]
Yes, of course!

**Comment by kevin36524** [comment]
Thanks @pcuenca, 

I have raised the PR for giving more detailed error https://github.com/huggingface/swift-transformers/pull/114
