### ISSUE TITLE
Are there plans to provide a Kotlin version?

### ISSUE THREAD

**Issue by twiceyuan** [huggingface/swift-transformers#12]
It would be nice to see transformers library available in different languages. Kotlin is a language that has a similar syntax to Swift and is widely used among Android developers. I would like to know if there is a plan to provide a Kotlin version of the transformers library to facilitate the use of HuggingFace models in scenarios such as Android and Java server-side development?

**Comment by pcuenca** [comment]
I'm not familiar enough with that ecosystem to understand how a Kotlin implementation would help the community. My understanding is that there are various ML engines for Android, I'm not sure a single Kotlin codebase could be applied to all. Do you have any insight here @xenova?

**Comment by xenova** [comment]
> Do you have any insight here @xenova?

https://developer.android.com/ml gives a nice overview for the two paths which are typically taken for ML on android:
1. Use [ml-kit](https://developers.google.com/ml-kit) for common use-cases (e.g., face detection, barcode scanning)
2. Use [tensorflow lite](https://www.tensorflow.org/lite) for custom use-cases. **This** would be the approach taken if we were to implement a transformers-like API for a language like Kotlin. And in a similar way to how [transformers.js](https://github.com/xenova/transformers.js) uses ONNX, "transformers-kotlin" would use tensorflow lite as a backend.

For Java, there is a [version of ONNX runtime](https://onnxruntime.ai/docs/get-started/with-java.html) which could be used, but this would still require tokenization and pipelines to be developed around it.

Although, to answer OP's question:

> I would like to know if there is a plan to provide a Kotlin version of the transformers library

The answer (for now) is that we haven't made any plans for it, but this doesn't stop someone in the community from picking up the project and implementing the "transformers API" 😇 ... After all, that's what I did for transformers.js 😉
