### ISSUE TITLE
StableCode Fails During Inference (stabilityai/stablecode-completion-alpha-3b-4k)

### ISSUE THREAD

**Issue by JustinMeans** [huggingface/swift-transformers#13]
[stabilityai/stablecode-completion-alpha-3b-4k](https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k) fails at the assert [here](https://github.com/huggingface/swift-transformers/blob/a6751372186eca1d928796b2f84b848cbaf9d2d7/Sources/Models/LanguageModel.swift#L130) but converts successfully using:
`python -m exporters.coreml --model=stabilityai/stablecode-completion-alpha-3b-4k exported/`

<img width="1398" alt="Screenshot 2023-08-09 at 3 44 43 AM" src="https://github.com/huggingface/swift-transformers/assets/46542161/a5498d5e-f56f-44d6-9498-9d4edf266ff2">

It's a gpt_neox model with GPTNeoXForCausalLM architecture.

When removing the assert and re-running, the SwiftChat app is able to load and run the model, but generates gibberish.

<img width="901" alt="Screenshot 2023-08-09 at 3 46 51 AM" src="https://github.com/huggingface/swift-transformers/assets/46542161/2877b64d-7caf-4f08-86b2-f01e4fadce5a">

I have the converted model currently uploading to HF but it's going to take a bit to complete.

**Comment by pcuenca** [comment]
Closing for now, feel free to reopen if appropriate!
