### ISSUE TITLE
"Demo App" link leads to a private repo rather than HF's public one

### ISSUE THREAD

**Issue by Norod** [huggingface/swift-transformers#15]
https://github.com/huggingface/swift-transformers/blob/a6751372186eca1d928796b2f84b848cbaf9d2d7/README.md?plain=1#L70

Should be https://github.com/huggingface/swift-chat rather than https://github.com/pcuenca/swift-chat

**Comment by pcuenca** [comment]
Thanks Doron!

**Comment by pcuenca** [comment]
Fixed by #14
