### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by juanpablofernandez** [huggingface/swift-transformers#24]
Have you considered lowering the minimum swift version required to use the package?

**Comment by pcuenca** [comment]
Hello @juanpablofernandez! As this is meant as an in-progress technology demonstration, I'd rather use the latest version for now. I'd prefer not to worry about backwards compatibility until the project is more mature, if possible. Is there anything specific that a previous Swift version would help with?

**Comment by pcuenca** [comment]
Closing for now. Feel free to reopen if you need to support older versions in production, and we can assess the effort!
