### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/swift-transformers#35]
Hi,
Is there a way to stream tokens in Swift?
Thank you!

**Comment by pcuenca** [comment]
Yes! You can provide a callback to the `generate` function and it will be invoked when new tokens are received. [This is an example of how to use it](https://github.com/huggingface/swift-chat/blob/8a6fd567bdfcb8f71561f14394528ac5faef959d/SwiftChat/ContentView.swift#L94). Is that what you were looking for?

**Comment by fakerybakery** [comment]
Yes, thank you so much!
