### ISSUE TITLE
TinyLlama

### ISSUE THREAD

**Issue by thejefflarson** [huggingface/swift-transformers#44]
Hi!

I'm fiddling with [TinyLlama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) and trying to get it to work. First I ran:

`python -m exporters.coreml -m TinyLlama/TinyLlama-1.1B-Chat-v1.0 exported/ --feature "text-generation" --quantize float32`

(I also tried quantizing it to `float16`.)

To convert it to CoreML and then I created a singleton loader class to access it:

```swift
class LLM {
    static var shared: LanguageModel = {
        let url = Bundle.main.url(forResource: "TinyLlama", withExtension: "mlmodelc")!
        return try! LanguageModel.loadCompiled(url: url, computeUnits: .cpuAndGPU)
    }()
}
```

And finally I ran something like this:

```swift
do {
    let config = GenerationConfig(maxNewTokens: 256, doSample: true, temperature: 0.7, topK: 50, topP: 0.95)
    let output = try await LLM.shared.generate(config: config, prompt: prompt)
} catch {
    print("Error \(error)")
}
```

And it prints out gibberish, specifically a list of `<unk>` and `<\s>` (eos) tokens. Any thoughts on what I'm doing wrong here?

**Comment by pcuenca** [comment]
Your process looks good to me! Did you verify that the tokenizer files are being found and loaded correctly? This depends on a custom metadata field added to the Core ML package, but it should be added by `exporters`.

I have been testing TinyLlama myself, but in a work-in-progress dev branch. I can replicate everything in `main` to see if there's something I'm missing now.

**Comment by thejefflarson** [comment]
Hm,  I'm not sure, what is the name of the field? I'm not seeing a tokenizer field in the xcode list, is there a way to check?
<img width="410" alt="Screenshot 2024-02-09 at 11 41 59 AM" src="https://github.com/huggingface/swift-transformers/assets/55365/9e07b120-8409-41f4-926a-047ad597de39">

**Comment by pcuenca** [comment]
Hi @thejefflarson, it's `co.huggingface.exporters.name` and it's correct – the tokenizer files will be downloaded from that location in the Hub.

I've been testing and it looks like it's a bug with top-p sampling. After conversion (using `float16`), the following works:

```bash
swift run transformers "I" --max-length 128 --compute-units cpuAndGPU /Users/pedro/Desktop/LLMs/TinyLlama-1.1B-Chat-v1.0-exporters.mlmodelc
```

It uses greedy sampling. If I change the CLI [here](https://github.com/huggingface/swift-transformers/blob/564442fba36b0b694d730a62d0593e5f54043b55/Sources/TransformersCLI/main.swift#L70) with the following:

```swift
        var config = model.defaultGenerationConfig
        config.doSample = true
        config.maxNewTokens = maxLength
        config.temperature = 0.7
        config.topK = 50
        config.topP = 0.95
```

Then I see a lot of `<unk>` tokens as you described. If I then comment the `topP` line, generated text is again reasonable.

So we need to check why `topP` is not working as expected (at least in combination with the other parameters).

**Comment by pcuenca** [comment]
cc @jkrukowski too

**Comment by jkrukowski** [comment]
> cc @jkrukowski too

topK and topP seem to generate a reasonable text if used exclusively, will look into it

**Comment by jkrukowski** [comment]
https://github.com/huggingface/swift-transformers/pull/49

**Comment by pcuenca** [comment]
@thejefflarson I think @jkrukowski's change should fix this, feel free to reopen if you still observe anything wrong!

**Comment by thejefflarson** [comment]
Thank you I’ll give it a try!
