### ISSUE TITLE
Support canceling the download of the model?

### ISSUE THREAD

**Issue by maiqingqiang** [huggingface/swift-transformers#58]
I found that these codes seem to support canceling downloads.

https://github.com/huggingface/swift-transformers/blob/ae3ce32a833faad20cab1d2eedc4ad8d25a86d41/Sources/Hub/HubApi.swift#L167

https://github.com/huggingface/swift-transformers/blob/ae3ce32a833faad20cab1d2eedc4ad8d25a86d41/Sources/Hub/Downloader.swift#L94-L96

**Comment by maiqingqiang** [comment]
Can expose these methods for external call?

**Comment by DePasqualeOrg** [comment]
@maiqingqiang, were you able to implement this?

**Comment by maiqingqiang** [comment]
> @maiqingqiang, were you able to implement this?

Yes, I have implemented a simple version, but it's not the best implementation. 
https://github.com/maiqingqiang/ChatMLX/blob/2107e65664a522654463575bd514874016676b8f/ChatMLX/Utilities/Huggingface/HubApi.swift#L356

I plan to develop a real Hugging Face downloader. Currently, the downloader provided by swift-transformers stores files differently than the Python version. I hope that swift-transformers can share `~/.cache/huggingface` with the Python version.
https://huggingface.co/docs/huggingface_hub/guides/cli#huggingface-cli-download

**Comment by DePasqualeOrg** [comment]
That would be great! Currently LLM apps tend to store models in different locations, so it would be great if we could standardize on one location. However, on iOS I think we're limited to storing files in the app directory or app group directory.

**Comment by johnmai-dev** [comment]
> That would be great! Currently LLM apps tend to store models in different locations, so it would be great if we could standardize on one location. However, on iOS I think we're limited to storing files in the app directory or app group directory.

Currently, I have completed the scan for `~/.cache/huggingface`, and the download function is under development. 
https://github.com/johnmai-dev/HuggingfaceHub/blob/main/Tests/HuggingfaceHubTests/CacheManagerTests.swift
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/58b8724c-fa81-45b6-a1a7-ebc93c495ed2">


@DePasqualeOrg  If you're interested, feel free to join us in building it together. The goal is to port https://github.com/huggingface/huggingface_hub to Swift.

Swift HuggingfaceHub Repo: https://github.com/johnmai-dev/HuggingfaceHub

**Comment by DePasqualeOrg** [comment]
Thanks for taking the initiative, @johnmai-dev! I'll follow the progress in the new repo and see how I can help.

**Comment by johnmai-dev** [comment]
Hello @pcuenca , I am porting Python's huggingface_hub to Swift.  Initially, I wanted to port Python's huggingface_hub to swift-transformers, but that would require significant changes to swift-transformers. I also hope that swift-transformers will focus solely on transformers.

Do you think what I'm doing is feasible, or do you have any suggestions?

https://github.com/johnmai-dev/HuggingfaceHub
